### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by danstender** [Ensighten/udnssdk#23]
Hi Joseph,
we're packaging Terraform for Debian and want to add the SDK as a package. Could you please put the license under a (free) license, we can't include it like it is now.
Thanx in advance,
Daniel

**Comment by josephholsten** [comment]
I'll get that to you as soon as I can.

**Comment by danstender** [comment]
Great! Thanks for the quick reply.

Best,
Daniel

**Comment by josephholsten** [comment]
resolved in #24
